const projectsData = {
    "2022": [
        { id: 1, title: "AI-powered Campus Navigation System", description: "A mobile app using AI and AR for effortless campus navigation", students: "Alice Johnson, Bob Smith", supervisor: "Dr. Emily Brown", tags: ["AI", "AR", "Mobile App"] },
        { id: 2, title: "Blockchain-based Academic Credential Verification", description: "Secure and transparent system for verifying academic credentials", students: "Charlie Davis, David Wilson", supervisor: "Prof. Michael Green", tags: ["Blockchain", "Security", "Web Development"] },
    ],
    "2023": [
        { id: 3, title: "AI-Enhanced Learning Management System", description: "Personalized learning platform with AI-driven content recommendations", students: "Eve Taylor, Frank Anderson", supervisor: "Dr. Sarah White", tags: ["AI", "Education Tech", "Web Development"] },
        { id: 4, title: "Quantum-Resistant Cryptography Implementation", description: "Developing and implementing post-quantum cryptographic algorithms", students: "Grace Lee, Henry Martinez", supervisor: "Prof. Robert Black", tags: ["Cryptography", "Quantum Computing", "Security"] },
    ],
    "2024": [
        { id: 5, title: "Currently", description: "A Household electricty consumption monitoring solution", students: "Kiran Babu,Indrajith S Nair,Sidharth Manikuttan,Anit Thomas", supervisor: "Prof. Jikku Thomas", tags: ["IoT", "App Development", "FireBase", "React Native"] },
        { id: 6, title: "EduNet", description: "Professional Networking and Event Engagement App for Students and Alumni", students: "Kennith Joseph, Amiya Hidayathulla,Melby Mariam Chandy,Akshay CA", supervisor: "Prof. Smitha Jacob", tags: ["Flutter", "App Development", "REST API"] },
        { id: 7, title: "LegalEase AI", description: "LegalEase is a web application that provides users with accessible legal guidance, information on specific laws, and connections to specialized legal experts.", students: "Agnel Brigit Shaji,Akash Benny,Rohan Joshy,Sereena Mariam Saji", supervisor: "Dr.Praseetha V.M", tags: ["Dialogflow", "HTML", "CSS", "JavaScript", "Firebase"] },
        { id: 8, title: "SecureWin", description: "A blockchain-based lottery system enchancing transparency and security in Kerala.", students: "Hridya Mathew,Jebin Tom,Vinny Elz Vincent,Tini Treesa Joseph", supervisor: "Prof.Angitha George", tags: ["Blockchain", "Flutter", "Firebase", "HTML", "CSS", "JavaScript", "Twilio"] },
        { id: 9, title: "MyClinicMate", description: "A online platform for managing medical appointments,allows patients to book appointments, find doctors, and receive notifications, while doctors can manage their schedules and provide patient updates.", students: "Abhinand R,Sona Binu,Theres Boby,Theresa Shaji", supervisor: "Prof.Ashly Thomas", tags: [] },
        { id: 10, title: "MeetMyHelper", description: "MeetMyHelper is a platform for easily finding, booking, and managing caregiving services.", students: "Kavya K A,Liya Tony,Maria Joe,Nayana Tony", supervisor: "Prof.Jibin Philip", tags: ["React", "Firebase"] },
        { id: 11, title: "JourneySync", description: "Not Available", students: "Melvin Devasia,Adithyan B,Alishya Elezabath Tomy,Akhil Sabu", supervisor: "Prof.Dyni Thomas", tags: [] },
        { id: 12, title: "Voltz", description: "Not Available", students: "Aadithyaa MD,Abel Abraham Philip,Sachin Philip,Thomas K Binu", supervisor: "Prof.Jikku Thomas", tags: [] },
        { id: 13, title: "MathMindCare", description: "MathMindCare is a platform designed to detect the likelihood of dyscalculia in children and, if needed, offers targeted tasks and training to help them improve their mathematical skills", students: "Celcia George,Riya Mariya George,Sneha Shaji,Tesna Treesa Benny", supervisor: "Prof. Mereen Thomas", tags: [] },
        { id: 14, title: "HomeConnect", description: "HomeConnect is a platform that helps users easily find and book PGs and hostels, while providing property owners with simple management tools.", students: "Shaine Thomas,Rogy Benni,Surya Saji,Linta John", supervisor: "Prof.Angitha George", tags: ["Flutter", "Firebase", "Google Map Services"] },
        { id: 15, title: "AgroGuide", description: "Web application that enables a direct marketplace connecting farmers and consumers, eliminating the need for intermediaries. Also  offers personalized crop recommendations based on soil parameters provided by users and provide educational resources based on best cultivation practices.", students: "Gopika M,Deepna Maria Jimson,Nandana Venugopal,Rose George", supervisor: "Prof.Thushara Sukumar", tags: ["JavaScript", "php", "Flask", "MySQL", "ML"] },
        { id: 16, title: "Curently", description: "A Household Energy Monitoring System to monitor electricity,set usage limits,know billing amounts", students: "Anit Thomas,Indrajith S Nair,Kiran Babu,Sidharth Manikuttan", supervisor: "Prof.Jikku Thomas", tags: ["IoT", "React Native", "Sustainability", "App Development"] },
        { id: 17, title: "EliteArena", description: "Elite Arena is a comprehensive esports platform designed to streamline the management of tournaments, providing tools for organizing competitions, team creation, and secure payment processing for both organizers and players.", students: "Joel Varghese,Noel Roy,Mohammed Aadhil Thahir,Alan Augustine", supervisor: "Prof.Bino Thomas", tags: ["HTML", "CSS", "JavaScript", "React", "MongoDB"] },
        { id: 18, title: "SmartHire", description: "Not Available", students: "Shifaz Abdul Kareem,Sarun Siby,Tobin Thomas,Abin Mathew Siby", supervisor: "Prof.Thushara Sukumar", tags: [] },
        { id: 19, title: "WorkEase", description: "Not Available", students: "Aayush.G,Devamanas S.S,Dona Sosa Joe", supervisor: "Prof.Dona Mary Cherian", tags: [] },
        { id: 20, title: "On-spot Mechanic", description: "A platform to bring mechanic services to users upon emergency situations based on their gps location.", students: "Sanjid S,Edwin Rajesh,Ajay Cyriac,Jithmon P Cherian", supervisor: "Prof.Jibin Philip", tags: ["Flutter", "Google Maps services", "Firebase"] },
        { id: 21, title: "Foodie Buddy", description: "A Recipe App", students: "Niketh A,Abin Varghese,Mathew Raino", supervisor: "Prof.Smitha Jacob", tags: ["Flutter", "Firebase"] }
    ]
};

export default projectsData; 